apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubecast
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubecast
  template:
    metadata:
      labels:
        app: kubecast
    spec:
      containers:
      - name: kubecast
        image: devvsaxena/kubecast:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: kubecast-service
spec:
  type: NodePort
  selector:
    app: kubecast
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30081 